/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2017-07-11 04:00:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc.jsp", out, false);
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>用户登录</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/css/base.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/css/login.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/css/lrtk.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function myBrowser(){\r\n");
      out.write("    var userAgent = navigator.userAgent; //取得浏览器的userAgent字符串\r\n");
      out.write("    var isOpera = userAgent.indexOf(\"Opera\") > -1;\r\n");
      out.write("    if (isOpera) {\r\n");
      out.write("        return \"Opera\"\r\n");
      out.write("    }; //判断是否Opera浏览器\r\n");
      out.write("    if (userAgent.indexOf(\"Firefox\") > -1) {\r\n");
      out.write("        return \"FF\";\r\n");
      out.write("    } //判断是否Firefox浏览器\r\n");
      out.write("    if (userAgent.indexOf(\"Chrome\") > -1){\r\n");
      out.write("\t  return \"Chrome\";\r\n");
      out.write("\t}\r\n");
      out.write("    if (userAgent.indexOf(\"Safari\") > -1) {\r\n");
      out.write("        return \"Safari\";\r\n");
      out.write("    } //判断是否Safari浏览器\r\n");
      out.write("    if (userAgent.indexOf(\"compatible\") > -1 && userAgent.indexOf(\"MSIE\") > -1 && !isOpera) {\r\n");
      out.write("        return \"IE\";\r\n");
      out.write("    }; //判断是否IE浏览器\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\tvar mb = myBrowser();\r\n");
      out.write("\tif (\"FF\" != mb && \"Chrome\" != mb && \"Safari\" != mb) {\r\n");
      out.write("\t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/browserDownload.jsp';\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar sessionInfo_userId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tif (sessionInfo_userId) {//如果登录,直接跳转到index页面\r\n");
      out.write("\t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/index';\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\ttoastr.options = {\r\n");
      out.write("\t\t\t\t\"closeButton\": false,\r\n");
      out.write("\t\t\t\t\"debug\": false,\r\n");
      out.write("\t\t\t\t\"positionClass\": \"toast-top-full-width\",\r\n");
      out.write("\t\t\t\t\"showDuration\": \"300\",\r\n");
      out.write("\t\t\t\t\"hideDuration\": \"1000\",\r\n");
      out.write("\t\t\t\t\"timeOut\": \"3000\",\r\n");
      out.write("\t\t\t\t\"extendedTimeOut\": \"1000\",\r\n");
      out.write("\t\t\t\t\"showEasing\": \"swing\",\r\n");
      out.write("\t\t\t\t\"hideEasing\": \"linear\",\r\n");
      out.write("\t\t\t\t\"showMethod\": \"fadeIn\",\r\n");
      out.write("\t\t\t\t\"hideMethod\": \"fadeOut\"\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t$('#loginform').form({\r\n");
      out.write("\t\t    url:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/login',\r\n");
      out.write("\t\t    onSubmit : function() {\r\n");
      out.write("\t\t    \tprogressLoad();\r\n");
      out.write("\t\t\t\tvar isValid = $(this).form('validate');\r\n");
      out.write("\t\t\t\tif(!isValid){\r\n");
      out.write("\t\t\t\t\ttoastr.warning(\"请输入用户名和密码\");\r\n");
      out.write("\t\t\t\t\tprogressClose();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn isValid;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t    success:function(result){\r\n");
      out.write("\t\t    \tresult = $.parseJSON(result);\r\n");
      out.write("\t\t    \tprogressClose();\r\n");
      out.write("\t\t    \tif (result.success) {\r\n");
      out.write("\t\t    \t\twindow.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/index';\r\n");
      out.write("\t\t    \t}else{\r\n");
      out.write("\t\t    \t\t/* $.messager.show({\r\n");
      out.write("\t\t    \t\t\ttitle:'提示',\r\n");
      out.write("\t\t    \t\t\tmsg:'<div class=\"light-info\"><div class=\"light-tip icon-tip\"></div><div>'+result.msg+'</div></div>',\r\n");
      out.write("\t\t    \t\t\tshowType:'show'\r\n");
      out.write("\t\t    \t\t}); */\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t    \t\ttoastr.error(result.msg);\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction submitForm(){\r\n");
      out.write("\t\t$('#loginform').submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction clearForm(){\r\n");
      out.write("\t\t$('#loginform').form('clear');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//回车登录\r\n");
      out.write("\tfunction enterlogin(e){\r\n");
      out.write("\t\tvar keynum = window.event ? e.keyCode : e.which;\r\n");
      out.write("\t\t//alert(keynum);\r\n");
      out.write("\t\tif (keynum == 13){\r\n");
      out.write("        \te.returnValue=false;\r\n");
      out.write("        \te.cancel = true;\r\n");
      out.write("        \t$('#loginform').submit();\r\n");
      out.write("    \t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onkeydown=\"enterlogin(event);\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"login\">\r\n");
      out.write("\t\t<form  method=\"post\" id=\"loginform\">\r\n");
      out.write("\t\t<div class=\"logo\"></div>\r\n");
      out.write("\t    <div class=\"login_form\" style=\"position:fixed;bottom:50px;\">\r\n");
      out.write("\t    \t<div class=\"user\">\r\n");
      out.write("\t        \t<input class=\"loginname_text_value easyui-validatebox\" type=\"text\" name=\"loginname\" data-options=\"required:true\" placeholder=\"请输入登录账号\" value=\"\" ></input>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t         <div class=\"user\">\r\n");
      out.write("\t            <input class=\"password_text_value easyui-validatebox\" type=\"password\" name=\"password\" data-options=\"required:true\" value=\"\"  placeholder=\"请输入密码\"></input>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t       \r\n");
      out.write("\t        <button class=\"blue-button\"  type=\"button\" onclick=\"submitForm()\"></button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\r\n");
      out.write("\t    \r\n");
      out.write("\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"position:fixed;bottom:0px;margin:0 auto;text-align:center;width:100%;color: #494848\">\r\n");
      out.write("\tCopyRight © 2016 厦门君沣信息科技. All Rights Reserved.\r\n");
      out.write("\t<br/>&nbsp;\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--[if lte IE 7]>\r\n");
      out.write("\t<div id=\"ie6-warning\"><p>您正在使用 低版本浏览器，在本页面可能会导致部分功能无法使用。建议您升级到 <a href=\"http://www.microsoft.com/china/windows/internet-explorer/\" target=\"_blank\">Internet Explorer 8</a> 或以下浏览器：\r\n");
      out.write("\t<a href=\"http://www.mozillaonline.com/\" target=\"_blank\">Firefox</a> / <a href=\"http://www.google.com/chrome/?hl=zh-CN\" target=\"_blank\">Chrome</a> / <a href=\"http://www.apple.com.cn/safari/\" target=\"_blank\">Safari</a> / <a href=\"http://www.operachina.com/\" target=\"_blank\">Opera</a></p></div>\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t/*ie6提示*/\r\n");
      out.write("\t\t#ie6-warning{width:100%;position:absolute;top:0;left:0;background:#fae692;padding:5px 0;font-size:12px}\r\n");
      out.write("\t\t#ie6-warning p{width:960px;margin:0 auto;}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<section id=\"h1\" class=\"jawbone-takeover-minimulti jawbone-hero\"><i class=\"jawbone-hero-image\" data-hero-image-fixed=\"true\" data-hero-image-fade=\"true\" data-hero-min-opacity=\".3\" style=\"opacity: 1.05;\"></i></section>\r\n");
      out.write("    \r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/login.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/views/login.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/login.jsp(3,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
